
package com.formation.soap.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://services.soap.formation.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param comptes
     * @return
     *     returns java.util.List<com.formation.soap.services.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addComptes", targetNamespace = "http://services.soap.formation.com/", className = "com.formation.soap.services.AddComptes")
    @ResponseWrapper(localName = "addComptesResponse", targetNamespace = "http://services.soap.formation.com/", className = "com.formation.soap.services.AddComptesResponse")
    @Action(input = "http://services.soap.formation.com/BanqueService/addComptesRequest", output = "http://services.soap.formation.com/BanqueService/addComptesResponse")
    public List<Compte> addComptes(
        @WebParam(name = "comptes", targetNamespace = "")
        List<Compte> comptes);

    /**
     * 
     * @return
     *     returns java.util.List<com.formation.soap.services.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://services.soap.formation.com/", className = "com.formation.soap.services.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://services.soap.formation.com/", className = "com.formation.soap.services.GetComptesResponse")
    @Action(input = "http://services.soap.formation.com/BanqueService/getComptesRequest", output = "http://services.soap.formation.com/BanqueService/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param compte
     */
    @WebMethod
    @RequestWrapper(localName = "addCompte", targetNamespace = "http://services.soap.formation.com/", className = "com.formation.soap.services.AddCompte")
    @ResponseWrapper(localName = "addCompteResponse", targetNamespace = "http://services.soap.formation.com/", className = "com.formation.soap.services.AddCompteResponse")
    @Action(input = "http://services.soap.formation.com/BanqueService/addCompteRequest", output = "http://services.soap.formation.com/BanqueService/addCompteResponse")
    public void addCompte(
        @WebParam(name = "compte", targetNamespace = "")
        Compte compte);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroToDh")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToDh", targetNamespace = "http://services.soap.formation.com/", className = "com.formation.soap.services.ConversionEuroToDh")
    @ResponseWrapper(localName = "ConversionEuroToDhResponse", targetNamespace = "http://services.soap.formation.com/", className = "com.formation.soap.services.ConversionEuroToDhResponse")
    @Action(input = "http://services.soap.formation.com/BanqueService/ConversionEuroToDhRequest", output = "http://services.soap.formation.com/BanqueService/ConversionEuroToDhResponse")
    public double conversionEuroToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns com.formation.soap.services.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://services.soap.formation.com/", className = "com.formation.soap.services.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://services.soap.formation.com/", className = "com.formation.soap.services.GetCompteResponse")
    @Action(input = "http://services.soap.formation.com/BanqueService/getCompteRequest", output = "http://services.soap.formation.com/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        Integer code);

}
